spring:

  application:
    name: spring-webflux

  profiles:
    active: local

  thymeleaf:
    prefix: /views

  cloud:
    gateway:
      routes:
        - id: spring-io
          uri: https://spring.io
          predicates:
            - Path=/spring/**

hello-world: default-real-world
---
spring:
  config:
    activate:
      on-profile: local

hello-world: local-real-world
---
spring:
  config:
    activate:
      on-profile: dev

hello-world: dev-real-world
---
spring:
  config:
    activate:
      on-profile: qa

hello-world: qa-real-world
---
spring:
  config:
    activate:
      on-profile: prod

hello-world: prod-real-world